"""
Example usage of the RAG+ system.

This script demonstrates how to use RAG+ for different domains
(mathematics, legal, medical) as described in the paper.
"""

from rag_plus import (
    RAGPlus,
    KnowledgeItem,
    ApplicationExample,
    LLMInterface,
    SimpleEmbeddingModel,
    OpenAILLM,
    OpenAIEmbeddingModel,
    compare_rag_vs_ragplus
)
import logging
import os

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class MockLLM(LLMInterface):
    """Mock LLM for demonstration purposes."""

    def generate(self, prompt: str, temperature: float = 0.0, max_tokens: int = 2048) -> str:
        """Generate mock responses based on prompt content."""
        # This is a simplified mock - in practice, you'd use a real LLM API
        if "conceptual knowledge" in prompt.lower():
            return """Question: What is the relationship between gross anatomy and microscopic anatomy in the study of human body structures?
Answer: Gross anatomy deals with structures visible to the naked eye, while microscopic anatomy involves the study of cells and tissues using a microscope. Both are complementary approaches to understanding the human body."""

        elif "procedural knowledge" in prompt.lower() or "combination formula" in prompt.lower():
            return """Question: How many ways can we choose 3 students from a class of 10 students?
Answer: Using the combination formula C(n,k) = n!/(k!(n-k)!), we have:
C(10,3) = 10!/(3!(10-3)!) = 10!/(3!×7!) = (10×9×8)/(3×2×1) = 720/6 = 120
Therefore, there are 120 ways to choose 3 students from 10."""

        elif "matching knowledge" in prompt.lower():
            return "case_1, case_2"

        else:
            # Default answer generation
            if "combination" in prompt.lower() or "choose" in prompt.lower():
                return """To solve this problem, I need to use the combination formula.
However, I should check if there are any constraints (like "at least one girl").
The answer depends on the specific constraints given in the problem."""

            return "This is a mock response. In a real implementation, this would be generated by an actual LLM."


def mathematics_example():
    """Example demonstrating RAG+ for mathematics domain."""
    print("\n" + "="*80)
    print("MATHEMATICS DOMAIN EXAMPLE")
    print("="*80 + "\n")

    # Initialize components
    llm = MockLLM()
    embedding_model = SimpleEmbeddingModel()
    rag_plus = RAGPlus(llm, embedding_model, top_k=3)

    # Define mathematical knowledge items
    knowledge_items = [
        KnowledgeItem(
            id="math_001",
            content="""Combination Formula: To choose k items from n without regard to order, use the combination formula: C(n, k) = n! / (k!(n-k)!). This is also denoted as "n choose k".""",
            knowledge_type="procedural",
            metadata={"category": "combinatorics", "domain": "mathematics"}
        ),
        KnowledgeItem(
            id="math_002",
            content="""Complementary Counting: When calculating combinations with constraints, it's often easier to calculate the total number of ways and subtract the invalid cases. This is particularly useful when the constraint is stated as "at least one" of something.""",
            knowledge_type="procedural",
            metadata={"category": "combinatorics", "domain": "mathematics"}
        ),
        KnowledgeItem(
            id="math_003",
            content="""Bayes' Theorem: Let A and B be two events, with P(B) > 0. Then the posterior probability of A given B is: P(A|B) = [P(B|A) × P(A)] / P(B)""",
            knowledge_type="procedural",
            metadata={"category": "probability", "domain": "mathematics"}
        )
    ]

    # Build corpus with application generation
    print("Building application corpus...")
    applications = rag_plus.build_corpus(
        knowledge_items,
        use_generation=True,
        use_matching=False
    )

    print(f"Generated {len(applications)} application examples\n")

    # Test query from the paper (Figure 1)
    test_query = """How many ways to choose 3 students from 6 boys and 4 girls, with at least one girl?"""

    print("Test Query:")
    print(test_query)
    print("\n" + "-"*80 + "\n")

    # Generate answer using RAG+
    answer = rag_plus.generate(test_query, task_type="math")

    print("RAG+ Answer:")
    print(answer)
    print("\n" + "="*80 + "\n")

    return rag_plus


def medical_example():
    """Example demonstrating RAG+ for medical domain."""
    print("\n" + "="*80)
    print("MEDICAL DOMAIN EXAMPLE")
    print("="*80 + "\n")

    llm = MockLLM()
    embedding_model = SimpleEmbeddingModel()
    rag_plus = RAGPlus(llm, embedding_model, top_k=3)

    # Define medical knowledge items
    knowledge_items = [
        KnowledgeItem(
            id="med_001",
            content="""Anatomy Definition: Anatomy includes those structures that can be seen grossly (without the aid of magnification) and microscopically (with the aid of magnification). Gross anatomy deals with structures visible to the naked eye, while microscopic anatomy (histology) involves the study of cells and tissues using a microscope.""",
            knowledge_type="conceptual",
            metadata={"category": "anatomy", "domain": "medical"}
        ),
        KnowledgeItem(
            id="med_002",
            content="""Peripheral Artery Disease (PAD): PAD is caused by atherosclerosis in the arteries supplying the lower extremities. Key symptoms include claudication (pain with exertion relieved by rest), weak or absent pulses, and in severe cases, erectile dysfunction. Risk factors include diabetes, hypertension, smoking, and coronary artery disease.""",
            knowledge_type="conceptual",
            metadata={"category": "cardiology", "domain": "medical"}
        ),
        KnowledgeItem(
            id="med_003",
            content="""Aortoiliac Atherosclerosis (Leriche Syndrome): Occlusion or severe stenosis of the terminal aorta and iliac arteries causes the triad of: 1) claudication in buttocks and thighs, 2) absent or diminished femoral pulses, and 3) erectile dysfunction in males. It's associated with cardiovascular risk factors.""",
            knowledge_type="procedural",
            metadata={"category": "vascular", "domain": "medical"}
        )
    ]

    # Build corpus
    print("Building application corpus...")
    applications = rag_plus.build_corpus(
        knowledge_items,
        use_generation=True,
        use_matching=False
    )

    print(f"Generated {len(applications)} application examples\n")

    # Test query similar to paper's MedQA example
    test_query = """A 67-year-old man presents with erectile dysfunction and deep burning buttock pain when walking that is relieved by rest. He has weak femoral pulses. Past medical history includes diabetes, hypertension, and a 40 pack-year smoking history. What is the most specific etiology?"""

    print("Test Query:")
    print(test_query)
    print("\n" + "-"*80 + "\n")

    answer = rag_plus.generate(test_query, task_type="medical")

    print("RAG+ Answer:")
    print(answer)
    print("\n" + "="*80 + "\n")

    return rag_plus


def legal_example():
    """Example demonstrating RAG+ for legal domain."""
    print("\n" + "="*80)
    print("LEGAL DOMAIN EXAMPLE")
    print("="*80 + "\n")

    llm = MockLLM()
    embedding_model = SimpleEmbeddingModel()
    rag_plus = RAGPlus(llm, embedding_model, top_k=2)

    # Define legal knowledge items (from Chinese Criminal Law)
    knowledge_items = [
        KnowledgeItem(
            id="law_001",
            content="""Article 234 (Intentional Injury): Whoever intentionally harms the body of another person shall be sentenced to fixed-term imprisonment of not more than three years, criminal detention, or public surveillance. Whoever commits the crime mentioned in the preceding paragraph and causes serious injury to another person shall be sentenced to fixed-term imprisonment of not less than three years but not more than ten years; Whoever causes death or serious disability by using particularly cruel means shall be sentenced to fixed-term imprisonment of not less than ten years, life imprisonment, or death penalty.""",
            knowledge_type="procedural",
            metadata={"category": "criminal_law", "article": "234", "domain": "legal"}
        ),
        KnowledgeItem(
            id="law_002",
            content="""Sentencing Considerations: When determining sentences, courts must consider: 1) The severity of the injury (minor, serious, death), 2) The means used (especially if particularly cruel), 3) Mitigating factors (self-defense, surrender, first offense), 4) Aggravating factors (weapons, multiple victims, premeditation).""",
            knowledge_type="procedural",
            metadata={"category": "criminal_law", "domain": "legal"}
        )
    ]

    # Build corpus
    print("Building application corpus...")
    applications = rag_plus.build_corpus(
        knowledge_items,
        use_generation=True,
        use_matching=False
    )

    print(f"Generated {len(applications)} application examples\n")

    # Test query for sentencing prediction
    test_query = """A person intentionally injured another with a weapon, causing first-degree minor injuries. The defendant has no prior criminal record and voluntarily surrendered. What is the appropriate sentence range?
A) Less than or equal to 36 months
B) Greater than 36 months and less than or equal to 120 months
C) Greater than 120 months"""

    print("Test Query:")
    print(test_query)
    print("\n" + "-"*80 + "\n")

    answer = rag_plus.generate(test_query, task_type="legal")

    print("RAG+ Answer:")
    print(answer)
    print("\n" + "="*80 + "\n")

    return rag_plus


def save_and_load_example():
    """Example demonstrating saving and loading corpus."""
    print("\n" + "="*80)
    print("SAVE AND LOAD CORPUS EXAMPLE")
    print("="*80 + "\n")

    llm = MockLLM()
    embedding_model = SimpleEmbeddingModel()
    rag_plus = RAGPlus(llm, embedding_model)

    # Create a small corpus
    knowledge_items = [
        KnowledgeItem(
            id="demo_001",
            content="The Pythagorean theorem states that in a right triangle, a² + b² = c²",
            knowledge_type="conceptual"
        )
    ]

    print("Building corpus...")
    rag_plus.build_corpus(knowledge_items, use_generation=True)

    # Save corpus
    print("Saving corpus to files...")
    rag_plus.save_corpus(
        knowledge_path="./knowledge_corpus.json",
        applications_path="./applications_corpus.json"
    )

    # Create new RAG+ instance and load corpus
    print("Loading corpus into new RAG+ instance...")
    rag_plus_new = RAGPlus(llm, embedding_model)
    rag_plus_new.load_corpus(
        knowledge_path="./knowledge_corpus.json",
        applications_path="./applications_corpus.json"
    )

    print("Corpus loaded successfully!")
    print(f"Knowledge items: {len(rag_plus_new.retriever.knowledge_corpus)}")
    print(f"Application examples: {len(rag_plus_new.retriever.application_corpus)}")
    print("\n" + "="*80 + "\n")


def openai_example():
    """Example demonstrating RAG+ with real OpenAI API."""
    print("\n" + "="*80)
    print("OPENAI SDK INTEGRATION EXAMPLE")
    print("="*80 + "\n")

    # Check if API key is available
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("⚠️  OPENAI_API_KEY not found in environment variables.")
        print("This example will be skipped. To run it:")
        print("1. Set your OpenAI API key: export OPENAI_API_KEY='your-key-here'")
        print("2. Or pass it directly when initializing OpenAILLM(api_key='your-key')\n")
        return

    try:
        # Initialize OpenAI components
        print("Initializing OpenAI LLM and Embedding Model...")
        llm = OpenAILLM(model="gpt-3.5-turbo")
        embedding_model = OpenAIEmbeddingModel(model="text-embedding-3-small")

        # Initialize RAG+ with OpenAI
        rag_plus = RAGPlus(llm, embedding_model, top_k=2)

        # Define a simple knowledge item
        knowledge_items = [
            KnowledgeItem(
                id="calc_001",
                content="""Power Rule for Derivatives: The derivative of x^n is n*x^(n-1). This is one of the most fundamental rules in calculus.""",
                knowledge_type="procedural",
                metadata={"category": "calculus", "domain": "mathematics"}
            )
        ]

        # Build corpus
        print("Building application corpus using OpenAI...")
        applications = rag_plus.build_corpus(
            knowledge_items,
            use_generation=True,
            use_matching=False
        )

        print(f"✓ Generated {len(applications)} application examples\n")

        # Test query
        test_query = "What is the derivative of x^3?"

        print("Test Query:")
        print(test_query)
        print("\n" + "-"*80 + "\n")

        # Generate answer using RAG+ with OpenAI
        print("Generating answer with OpenAI GPT-3.5-turbo...")
        answer = rag_plus.generate(test_query, task_type="math")

        print("RAG+ Answer:")
        print(answer)
        print("\n" + "="*80 + "\n")

    except Exception as e:
        logger.error(f"Error in OpenAI example: {e}")
        print(f"⚠️  Error: {e}")
        print("Make sure you have a valid OpenAI API key and sufficient credits.\n")


def main():
    """Run all examples."""
    print("""
╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║                          RAG+ IMPLEMENTATION DEMO                            ║
║                                                                              ║
║     Enhancing Retrieval-Augmented Generation with Application-Aware         ║
║                            Reasoning                                         ║
║                                                                              ║
║                    Based on the paper by Yu Wang et al.                      ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
    """)

    # Check if OpenAI API key is available
    has_openai = os.environ.get("OPENAI_API_KEY") is not None

    print("\n📋 CONFIGURATION:")
    print(f"   OpenAI API Key: {'✓ Found' if has_openai else '✗ Not found (will use mock LLM)'}")
    print()

    # Run examples for different domains
    try:
        if has_openai:
            print("\n[1/5] Running OpenAI Integration Example...")
            openai_example()

            print("\n[2/5] Running Mathematics Example (Mock)...")
        else:
            print("\n[1/4] Running Mathematics Example (Mock)...")

        mathematics_example()

        if has_openai:
            print("\n[3/5] Running Medical Example (Mock)...")
        else:
            print("\n[2/4] Running Medical Example (Mock)...")
        medical_example()

        if has_openai:
            print("\n[4/5] Running Legal Example (Mock)...")
        else:
            print("\n[3/4] Running Legal Example (Mock)...")
        legal_example()

        if has_openai:
            print("\n[5/5] Running Save/Load Example...")
        else:
            print("\n[4/4] Running Save/Load Example...")
        save_and_load_example()

        print("\n" + "="*80)
        print("All examples completed successfully!")
        print("="*80 + "\n")

        if not has_openai:
            print("💡 TIP: Set OPENAI_API_KEY environment variable to try OpenAI integration!")
            print("   export OPENAI_API_KEY='your-api-key-here'\n")

    except Exception as e:
        logger.error(f"Error running examples: {e}", exc_info=True)
        raise


if __name__ == "__main__":
    main()
